### ISSUE TITLE
IndexOutOfRangeException running TestServer_Console

### ISSUE THREAD

**Issue by pedrolcl** [Astn/JSON-RPC.NET#103]
Feeding TestServer_Console with this Json document (with 1 extra positional argument):

{'method':'add','params':[1,2,3],'id':2}

Produces an IndexOutOfRangeException in Handler.cs:255 which is not handled. Stack trace:

System.IndexOutOfRangeException
  HResult=0x80131508
  Message=Índice fuera de los límites de la matriz.
  Source=AustinHarris.JsonRpc
  StackTrace:
   at AustinHarris.JsonRpc.Handler.Handle(JsonRequest Rpc, Object RpcContext) in C:\Users\plopezc\source\repos\JsonRpcNet\Json-Rpc\Handler.cs:line 255
   at AustinHarris.JsonRpc.JsonRpcProcessor.ProcessInternal(String sessionId, String jsonRpc, Object jsonRpcContext) in C:\Users\plopezc\source\repos\JsonRpcNet\Json-Rpc\JsonRpcProcessor.cs:line 100
   at AustinHarris.JsonRpc.JsonRpcProcessor.<>c.<Process>b__3_0(Object _) in C:\Users\plopezc\source\repos\JsonRpcNet\Json-Rpc\JsonRpcProcessor.cs:line 39
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()

**Comment by Astn** [comment]
Fixed in #104 
Thanks @pedrolcl
