### ISSUE TITLE
How to handle TargetInvocationException?

### ISSUE THREAD

**Issue by samkoen** [Astn/JSON-RPC.NET#37]
When I call for many JsonRpcMethod, I receive after a while a TargetInvocationException exception, and the server fails. 
Why this exception occurred? And how can I catch it (to restart the server for example) 
Thanks!
The version used is 1.0.4.0

**Comment by Astn** [comment]
Can you reproduce with 1.0.4.29 ? It's available on nuget, or as a tag here on github.

**Comment by Astn** [comment]
Also, could you post the stack trace for the exception please?

**Comment by samkoen** [comment]
I found the issue:

The issue was that a AccessViolationException occurred on the JSonRpcMethod, and this AccessViolationException is not catched by a regular try-catch.

When it occurred, the RPC-JSON server fails.

 

 

System.Reflection.TargetInvocationException was unhandled

  _HResult=-2146232828

  _message=Exception has been thrown by the target of an invocation.

  HResult=-2146232828

  IsTransient=false

  Message=Exception has been thrown by the target of an invocation.

  Source=mscorlib

  StackTrace:

       at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)

       at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)

       at System.Delegate.DynamicInvokeImpl(Object[] args)

       at System.Delegate.DynamicInvoke(Object[] args)

       at AustinHarris.JsonRpc.Handler.Handle(JsonRequest Rpc, Object RpcContext) in d:\temp\tmp52ED\Json-Rpc\Handler.cs:line 320

       at AustinHarris.JsonRpc.JsonRpcProcessor.ProcessInternal(String sessionId, String jsonRpc, Object jsonRpcContext) in d:\temp\tmp52ED\Json-Rpc\JsonRpcProcessor.cs:line 107

       at AustinHarris.JsonRpc.JsonRpcProcessor.ProcessJsonRpcState(String sessionId, JsonRpcStateAsync async, Object jsonRpcContext) in d:\temp\tmp52ED\Json-Rpc\JsonRpcProcessor.cs:line 41

       at AustinHarris.JsonRpc.JsonRpcProcessor.<Process>b__2(Object _async) in d:\temp\tmp52ED\Json-Rpc\JsonRpcProcessor.cs:line 31

       at System.Threading.Tasks.Task.InnerInvoke()

       at System.Threading.Tasks.Task.Execute()

       at System.Threading.Tasks.Task.ExecutionContextCallback(Object obj)

       at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)

       at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)

       at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot)

       at System.Threading.Tasks.Task.ExecuteEntry(Boolean bPreventDoubleExecution)

       at System.Threading.Tasks.Task.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()

       at System.Threading.ThreadPoolWorkQueue.Dispatch()

       at System.Threading._ThreadPoolWaitCallback.PerformWaitCallback()

  InnerException: System.AccessViolationException

       _HResult=-2147467261

       _message=Attempted to read or write protected memory. This is often an indication that other memory is corrupt.

       HResult=-2147467261

       IsTransient=false

       Message=Attempted to read or write protected memory. This is often an indication that other memory is corrupt.

       Source=System.Data.SqlServerCe

       StackTrace:

            at System.Data.SqlServerCe.NativeMethodsHelper.CompileQueryPlan(IntPtr pQpCommand, String pwszCommandText, ResultSetOptions options, IntPtr[] pParamNames, IntPtr prgBinding, Int32 cDbBinding, IntPtr& pQpPlan, IntPtr pError)

            at System.Data.SqlServerCe.NativeMethods.CompileQueryPlan(IntPtr pQpCommand, String pwszCommandText, ResultSetOptions options, IntPtr[] pParamNames, IntPtr prgBinding, Int32 cDbBinding, IntPtr& pQpPlan, IntPtr pError)

            at System.Data.SqlServerCe.SqlCeCommand.CompileQueryPlan()

            at System.Data.SqlServerCe.SqlCeCommand.ExecuteCommand(CommandBehavior behavior, String method, ResultSetOptions options)

           at System.Data.SqlServerCe.SqlCeCommand.ExecuteReader(CommandBehavior behavior)

            at System.Data.SqlServerCe.SqlCeCommand.ExecuteDbDataReader(CommandBehavior behavior)

            at System.Data.Common.DbCommand.ExecuteReader()

            at System.Data.Linq.SqlClient.SqlProvider.Execute(Expression query, QueryInfo queryInfo, IObjectReaderFactory factory, Object[] parentArgs, Object[] userArgs, ICompiledSubQuery[] subQueries, Object lastResult)

            at System.Data.Linq.SqlClient.SqlProvider.ExecuteAll(Expression query, QueryInfo[] queryInfos, IObjectReaderFactory factory, Object[] userArguments, ICompiledSubQuery[] subQueries)

            at System.Data.Linq.SqlClient.SqlProvider.System.Data.Linq.Provider.IProvider.Execute(Expression query)

            at System.Data.Linq.DataQuery`1.System.Linq.IQueryProvider.Execute[S](Expression expression)

            at System.Linq.Queryable.Count[TSource](IQueryable`1 source)

            at DeviceSystemManager.DataLayer.DBPersistencyDbml.Select(SelectCommand dbSelect) in c:\Users\skoen\Documents\SVN\Src\C#\projects\EncoderDecoder\MediatorMain\DataLayer\DBPersistencyDbml.cs:line 249

            at DeviceSystemManager.RPC.DeviceSystemManagerRpcService.Select(Object selectJson) in c:\Users\skoen\Documents\SVN\Src\C#\projects\EncoderDecoder\MediatorMain\RPC\DeviceSystemManagerRpcService.cs:line 169

       InnerException:

**Comment by Astn** [comment]
http://stackoverflow.com/questions/3469368/how-to-handle-accessviolationexception

Hmm..

**Comment by Astn** [comment]
From the above link:
In .NET 4.0, the runtime handles certain exceptions raised as Windows Structured Error Handling (SEH) errors as indicators of Corrupted State. These Corrupted State Exceptions (CSE) are not allowed to be caught by your standard managed code. I won't get into the why's or how's here. Read this article about CSE's in the .NET 4.0 Framework:
--
So this isn't something we can fix.
