### ISSUE TITLE
how to remove session at runtime.

### ISSUE THREAD

**Issue by frndxyz** [Astn/JSON-RPC.NET#41]
@Astn  in my project many instance created with different key. and i want to dispose to any of them at runtime and any case
i can recreate it runtime again but it show me this error. it means key is not remove or disposed, so  how can i achieve this.

An exception of type 'System.ArgumentException' occurred in mscorlib.dll but was not handled in user code

Additional information: An item with the same key has already been added.

----
   at System.Collections.Generic.Dictionary`2.Insert(TKey key, TValue value, Boolean add)
   at AustinHarris.JsonRpc.SMD.AddService(String method, Dictionary`2 parameters, Dictionary`2 defaultValues) in d:\temp\tmp613C\Json-Rpc\SMDService.cs:line 41
   at AustinHarris.JsonRpc.JsonRpcService.buildService(String sessionID) in d:\temp\tmp613C\Json-Rpc\JsonRpcService.cs:line 60
   at AustinHarris.JsonRpc.JsonRpcService..ctor() in d:\temp\tmp613C\Json-Rpc\JsonRpcService.cs:line 14
   at Coinium.Server.Mining.Stratum.Service.StratumService..ctor(IShareManager shareManager) in e:\Coding\CoiniumServ\src\CoiniumServ\Server\Mining\Stratum\Service\StratumService.cs:line 39
   at lambda_method(Closure , Object[] )
   at Nancy.TinyIoc.TinyIoCContainer.ConstructType(Type requestedType, Type implementationType, ConstructorInfo constructor, NamedParameterOverloads parameters, ResolveOptions options)

**Comment by Astn** [comment]
`JsonRpc.Handler.GetSessionHandler ("someSessionId").Destroy();`
