### ISSUE TITLE
NuGet release and Json.NET

### ISSUE THREAD

**Issue by SommerEngineering** [Astn/JSON-RPC.NET#44]
I have tried to use JSON-RPC.NET with the latest Json.NET version 7.0.1. But it seems not to work with JSON-RPC.NET:

```
System.TypeInitializationException: The type initializer for 'AustinHarris.JsonRpc.Handler' threw an exception. ---> System.IO.FileLoadException: Could not load file or assembly 'Newtonsoft.Json, Version=6.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)

   at AustinHarris.JsonRpc.SMD..ctor()
   at AustinHarris.JsonRpc.Handler..ctor(String sessionId) in d:\temp\tmp52ED\Json-Rpc\Handler.cs:line 35
   at AustinHarris.JsonRpc.Handler..cctor() in d:\temp\tmp52ED\Json-Rpc\Handler.cs:line 29
   --- End of inner exception stack trace ---
   at AustinHarris.JsonRpc.Handler.DefaultSessionId()
   at AustinHarris.JsonRpc.JsonRpcService..ctor() in d:\temp\tmp52ED\Json-Rpc\JsonRpcService.cs:line 13
   at Example006.MyJSONRPCService..ctor()
   at Example006.Program.Main(String[] args)
```

**Comment by Astn** [comment]
JSON-RPC.NET 1.0.4.46
I upload the latest code to nuget. I tested it w/ json.net 8. Let me know if your still having issues with it.
https://www.nuget.org/packages/AustinHarris.JsonRpc/
